---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deploy
  namespace: default
spec:
  replicas: 4
# folgenden Abschnitt erst nachträglich mit den Erklährungen dazu:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1 
  selector:
    matchLabels:
      irgendein: label
  template:
    metadata:
      labels:
        irgendein: label
    spec:
      containers:
        - name: web
          image: nginx:latest

